# Generated by Django 5.0.7 on 2024-07-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
